Fixed Input Error For Python 2.7 and Stray print
The Program gave the following error in Pyhon 2.7:
LINE:   name = input()
  File "<string>", line 1, in <module>
NameError: name 'rock' is not defined

Fixed by using legacy input method which is compatible in both python 2.7 and 3

Fixed stray ' ( )  ' after selecting choice